# Generated by Django 4.1.7 on 2023-06-22 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanedcomment',
            name='cleaned_text',
        ),
        migrations.AddField(
            model_name='cleanedcomment',
            name='label',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='UrduComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('parent_id', models.CharField(default=None, max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateField(default=None)),
                ('update_at', models.DateTimeField()),
                ('label', models.CharField(default=None, max_length=255)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urcomment_video', to='youtube_app.youtubevideoid')),
            ],
        ),
        migrations.CreateModel(
            name='EmojiesClean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('parent_id', models.CharField(default=None, max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateField(default=None)),
                ('update_at', models.DateTimeField()),
                ('label', models.CharField(default=None, max_length=255)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eccomment_video', to='youtube_app.youtubevideoid')),
            ],
        ),
    ]
