# Generated by Django 4.2 on 2023-06-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_remove_cleanedcomment_cleaned_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='spamlabel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='UrduComment',
        ),
    ]
