# Generated by Django 4.2 on 2023-06-25 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0003_comments_spamlabel_delete_urducomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamCleanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('parent_id', models.CharField(default=None, max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateField(default=None)),
                ('update_at', models.DateTimeField()),
                ('cleaned_date', models.DateTimeField(auto_now_add=True)),
                ('spamlabel', models.CharField(default=None, max_length=255)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scomment_video', to='youtube_app.youtubevideoid')),
            ],
        ),
    ]
