# Generated by Django 4.1.7 on 2023-06-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0004_cleanedcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanedcomment',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
